site_name: LeadAR Documentation
theme:
  name: material
  logo: img/logo.png
  favicon: img/logo.png
  font:
    text: JetBrains Mono
    code: JetBrains Mono
  palette:
    scheme: slate # тёмная тема по умолчанию
    primary: orange
    accent: cyan
  features:
    - navigation.tabs
    - navigation.sections
    - search.highlight
    - content.code.copy

extra_css:
  - css/extra.css

extra_javascript:
  - javascript/extra.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - glightbox

nav:
  - Главная: index.md
  - AIO (Crypto):
      - Offers:
          - Adding new offer: aio-crypto/offers/new-offer.md
          - Offer adaptaion for AIO (google): aio-crypto/offers/offer-adapt-google.md
          - Adding Buyer UTM for campaigns: aio/users/buyer-utm.md
          - Creating new campaign: aio-crypto/campaigns/new-campaign.md
  - AIO (Sweeps):
      - Users:
          - Overview: aio/users/index.md
          - New User: aio/users/new-user.md
          - Adding Buyer UTM for campaigns: aio/users/buyer-utm.md
          - Change position: aio/users/positions.md
      - Domains:
          - Overview: aio/domains/index.md
          - Adding Domains: aio/domains/adding-domains.md
          - Domain Proxying: aio/domains/domain-proxying.md
          - Domain Recovery: aio/domains/domain-recovery.md
      - Servers:
          - Servers Purchase and Configuration: aio/servers/servers.md
      - Landing:
          - Overview: aio/landing/index.md
          - Adding New land: aio/landing/new-land.md
          - New Land Creation: aio/landing/create.md
          - Transfer Land from Keitaro: aio/landing/migrate.md
      - All Access: aio/all-access.md
      - Fix Template: aio/fix-template.md
      - WE DON'T USE IT NOW:
          - Overview: aio/we-dont-use/index.md
          - Destinations (Offers): aio/we-dont-use/destinations.md
          - Campaigns: aio/we-dont-use/campaigns.md
          - CustomLink: aio/we-dont-use/customlink.md
          - Adding Domains via AIO: aio/we-dont-use/adding-domains-aio.md
  - Keitaro:
      - Создание стандартного сетапа в кейтаро (Crypto): keitaro/standard-setup-crypto.md
      - Отключение ключа кампании: keitaro/disable-campaign-key.md
      - Создание оффера NCAPI: keitaro/offer-ncapi.md
      - Адаптация оффера под Google: keitaro/offer-google.md
      - Postback — отправка лида: keitaro/postback-lead.md
      - Сетап в кейтаро без кло: keitaro/setup-no-clo.md
      - Создание сетапа под facebookEK (conversionApi): keitaro/setup-facebookek.md
      - Preland — скрипт для выделения всех ссылок и перехода на оффер: keitaro/preland-script.md
  - Серверные сетапы:
      - Hostinger + Palladium: server/Hostinger+Palladium.md
      - Прокидываем в клауд домены: server/CloudScript.md
